# Generated by Django 5.2.4 on 2025-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_store_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("seller", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.CharField(max_length=255),
        ),
    ]
