# Generated by Django 5.2.4 on 2025-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
